# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Install Dependencies
      run: sudo apt install go-bindata mingw-w64
      
    - name: Build
      run: chmod +x buildall.sh && ./buildall.sh
    
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: buildFiles
        path: output
